export const MES_APP_ROLE = {
  // config app
  ACCESS_CONFIG_APP: "ACCESS_CONFIG_APP",
  CONFIG_APP_ADD: "CONFIG_APP_ADD",

  // TG KPI
  ACCESS_TG_KPI_APP: "ACCESS_TG_KPI_APP",
  TG_KPI_APP_ADD: "TG_KPI_APP_ADD",
};
